apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ggr-trafic
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - redirect.yaml
configMapGenerator:
  - name: ggr-trafic-config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ggr-trafic
    newName: ggr-trafic
    newTag: local
