# kubectl -n ggr-trafic create secret generic ggr-trafic-secrets \
#   --from-literal=admin-token='choisir-un-jeton' \
#   --from-literal=session-secret='choisir-un-secret-session' \
#   --from-literal=google-client-id='….apps.googleusercontent.com' \
#   --from-literal=google-client-secret='…'
apiVersion: v1
kind: Secret
metadata:
  name: ggr-trafic-secrets
type: Opaque
stringData:
  admin-token: "changer-moi"
  session-secret: "changer-moi-aussi"
  google-client-id: ""
  google-client-secret: ""
