apiVersion: v1
kind: Service
metadata:
  name: ggr-trafic
  labels:
    app.kubernetes.io/name: ggr-trafic
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ggr-trafic
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
