- op: replace
  path: /spec/tls
  value:
    - hosts:
        - ggr-trafic-test.k3s.lpb.ovh
      secretName: ggr-trafic-test-tls
- op: replace
  path: /spec/rules
  value:
    - host: ggr-trafic-test.k3s.lpb.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ggr-trafic
                port:
                  number: 8080
